name: blockchain_dapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  
  file_picker: 
  
   
  http: 
  animate_gradient:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter

  get: ^4.6.6

  web3modal_flutter: ^3.1.2
  flutter_ipfs: ^0.0.2
  animated_icon: ^0.0.9
  flutter_animated_button: ^2.0.3
  slider_button: ^2.1.0
  cached_network_image: ^3.3.1

dependency_overrides:
  http: 
  
  file_picker:

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
